print("give me two numbers please ")
num1 = input("number one is? ")
num2 = input("number two is? ")
num1=int(num1)
num2=int(num2)
print(str(num1) + "+" + str(num2) +"=" + str(num1 + num2))
print(str(num1) + "-" + str(num2) +"=" + str(num1 - num2))
print(str(num1) + "x" + str(num2) +"=" + str(num1 * num2))
print(str(num1) + "/" + str(num2) +"=" + str(num1 / num2))